### ISSUE TITLE
CSV File Wrapper

### ISSUE THREAD

**Issue by OlgaOvcharenko** [eth-easl/modyn#235]
Currently, there is only a binary file wrapper. For the Reddit benchmark, a CSV file wrapper is needed.

**Comment by vGsteiger** [comment]
Hi Olga, as you may have already seen, we're currently in the progress of porting the storage component to c++. If you feel comfortable in c++ feel free to already start thinking about how to port your MR to c++, otherwise we can make a new issue or if this is merged before my MR I can take over the translation. 

Let me know what you would prefer.

Thanks!

**Comment by MaxiBoether** [comment]
We have a CSV Wrapper :)
